- name: Setup Kubernetes Cluster
  become: true
  hosts: all
  vars:
    # kubernetes configurations
    k8s_minor_version: "{{ lookup('env', 'k8s_minor_version') }}"
    daemon_json: "{{ lookup('env', 'daemon_json') | from_json }}"
    virtual_ip: "{{ lookup('env', 'virtual_ip') }}"
  tasks:
  #- ansible.builtin.include_role:
  #    name: keepalived
  #  when: "'masters' in group_names"
  - ansible.builtin.include_role:
      name: docker
  - ansible.builtin.include_role:
      name: kubernetes
