- name: Create /etc/docker directory
  file:
    name: /etc/docker
    state: directory

- name: Config docker daemon.json
  ansible.builtin.template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  ignore_errors: true

- name: Ensure overlay module is loaded
  ansible.builtin.shell: modprobe overlay

- name: Ensure br_netfilter module is loaded
  ansible.builtin.shell: modprobe br_netfilter

- name: Make sure module is loaded when rebooting
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    state: present
    create: yes
    path: /etc/modules-load.d/docker.conf
  loop:
  - overlay
  - br_netfilter

- name: Create sysctl configuration for Kubernetes
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- shell: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Apply sysctl settings
  ansible.builtin.shell: sysctl --system
