- name: Install Docker for Ubuntu
  when: ansible_os_family == "Debian"
  block:
  - name: Add dependencies
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items:
    - ca-certificates

  - name: Create directory for Docker GPG key
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Remove previous docker gpg
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop:
    - /etc/apt/keyrings/docker.asc
    - /etc/apt/keyrings/docker.gpg
    - /etc/apt/sources.list.d/docker.list

  - name: Download Docker's GPG key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc

  - name: Set permissions for Docker's GPG key
    ansible.builtin.file:
      path: /etc/apt/keyrings/docker.asc
      mode: '0666'

  - name: Add Docker repository to Apt sources
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
      filename: docker

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: true

  - name: Install Docker
    when: k8s_minor_version | int >= 24
    ansible.builtin.apt:
      name: "{{ item }}"
      state: latest
    loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    ignore_errors: true

  - name: Install Docker
    when: k8s_minor_version | int < 24
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      allow_downgrade: true
    loop:
    - docker-ce=5:20.10.21*
    - docker-ce-cli=5:20.10.21*
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    ignore_errors: true

  - name: Stop docker service
    ansible.builtin.service: name=docker state=stopped enabled=yes

- name: Install Docker for CentOS
  when: ansible_os_family == "RedHat"
  block:
  - name: Add dependencies
    ansible.builtin.yum:
      name: "{{ item }}"
      state: present
    with_items:
    - device-mapper-persistent-data
    - lvm2

  - name: Remove previous docker gpg
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop:
    - /etc/yum.repos.d/docker.repo
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-Docker

  - name: Download Docker's GPG key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/gpg
      dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-Docker
    ignore_errors: true

  - name: Add Docker repository to Yum sources
    ansible.builtin.yum_repository:
      name: docker
      description: Docker CE Stable
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
      enabled: yes
      gpgcheck: no
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Docker

  - name: Install Docker
    when: k8s_minor_version | int >= 24
    ansible.builtin.yum:
      name: "{{ item }}"
      state: latest
    loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    ignore_errors: true

  - name: Install Docker
    when: k8s_minor_version | int < 24
    ansible.builtin.yum:
      name: "{{ item }}"
      state: present
      allow_downgrade: true
    loop:
    - docker-ce-3:20.10.21*
    #- docker-ce-cli-1:20.10.21*
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    ignore_errors: true

  - name: Stop docker service
    ansible.builtin.service:
      name: docker
      state: stopped
      enabled: yes
